FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
RUN npm install html2canvas jspdf
COPY . .
EXPOSE 5555
CMD ["npm", "run", "dev"]
# FROM node:20-alpine
# WORKDIR /app
# COPY package*.json ./
# RUN npm ci
# COPY . .
# EXPOSE 5555
# CMD ["npm", "run", "dev"]