version: "3.8"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    hostname: zookeeper
    env_file:
      - ./env/zookeeper.env
    ports:
      - "2181:2181"


  # брокер сообщений между общим хранилищем видеозаписей и [модулями детекции и трекинга]
  # можно ещё kafka-ui добавить
  record-storage-broker:
    image: confluentinc/cp-kafka:7.4.4
    container_name: record-storage-broker
    hostname: record-storage-broker
    depends_on:
      - zookeeper
    env_file:
      - ./env/record-storage-broker.env
    ports:
      - "9092:9092"
      - "29092:29092"


  # общее хранилище, в которое попадают все записи с камер
  entry-record-storage:
    image: minio/minio:latest
    container_name: entry-record-storage
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./env/entry-record-storage.env
    volumes:
      - ./volume/entry-record-storage:/data
    restart: unless-stopped

  entry-record-storage-initializer:
    image: minio/mc:latest
    container_name: entry-record-storage-initializer
    depends_on:
      - entry-record-storage
      - record-storage-broker
    env_file:
      - ./env/entry-record-storage.env
    volumes:
      - ./init/entry-record-storage.bash:/entry-record-storage.bash
    entrypoint: >
      /bin/sh -c "
      chmod +x /entry-record-storage.bash;
      /entry-record-storage.bash;
      "
  

  # вспомогательный сервис, в который MinIO будет слать уведомления: эдакая обёртка над Kafka
  notification-service:
    build:
      context: ./service/notification-service
    container_name: notification-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./service/notification-service/notification-service.env
    depends_on:
      - record-storage-broker
      - entry-record-storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://notification-service:8000/minio-webhook"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


  # хранилище выявленных треков
  track-storage:
    image: mongo:latest
    container_name: track-storage
    restart: always
    env_file:
      - ./env/track-storage.env
    ports:
      - "27017:27017"
    volumes:
      - ./volume/track-storage:/data/db
      - ./init/track-storage:/docker-entrypoint-initdb.d:ro

  track-storage-ui:
    image: mongo-express:latest
    container_name: track-storage-ui
    restart: always
    ports:
      - "7017:8081"
    env_file:
      - ./env/track-storage-ui.env
    depends_on:
      - track-storage


  # хранилище изображений, вырезанных из видео по трекам
  crop-storage:
    image: minio/minio:latest
    container_name: crop-storage
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9003:9001"
    env_file:
      - ./env/crop-storage.env
    volumes:
      - ./volume/crop-storage:/data
    restart: unless-stopped

  crop-storage-initializer:
    image: minio/mc:latest
    container_name: crop-storage-initializer
    depends_on:
      - crop-storage
    env_file:
      - ./env/crop-storage.env
    volumes:
      - ./init/crop-storage.bash:/crop-storage.bash
    entrypoint: >
      /bin/sh -c "
      chmod +x /crop-storage.bash;
      /crop-storage.bash;
      "


  # модуль формирования треков передвижения людей
  detection-tracking-module:
    build:
      context: ./module/detection-tracking-module
    container_name: detection-tracking-module
    restart: unless-stopped
    ports:
      - "6000:5000"
    depends_on:
      - track-storage
      - crop-storage
      - record-storage-broker
      - entry-record-storage
    env_file:
      - ./module/detection-tracking-module/detection-tracking-module.env
    volumes:
      - ./module/detection-tracking-module/uploads:/app/uploads
      - ./module/detection-tracking-module/models:/app/models


  # брокер сообщений между [модулями детекции и трекинга] и [модулями классификации]
  detection-broker:
    image: confluentinc/cp-kafka:7.4.4
    container_name: detection-broker
    hostname: detection-broker
    depends_on:
      - zookeeper
    env_file:
      - ./env/detection-broker.env
    ports:
      - "9093:9092"
      - "29093:29092"


  # модуль классификации наличия жилета
  classification-module:
    build:
      context: ./module/classification-module
    container_name: classification-module
    restart: unless-stopped
    ports:
      - "6001:5000"  
    env_file:
      - ./module/classification-module/classification-module.env
    depends_on:
      - detection-broker
      - accident-broker
      - crop-storage
    volumes:
      - ./module/classification-module/config:/app/config
      - ./module/classification-module/models:/app/models


  # брокер сообщений между [модулями классификации] и [регистратором инцидентов]
  accident-broker:
    image: confluentinc/cp-kafka:7.4.4
    container_name: accident-broker
    hostname: accident-broker
    depends_on:
      - zookeeper
    env_file:
      - ./env/accident-broker.env
    ports:
      - "9094:9092"
      - "29094:29092"
  