spring.application.name=accident-recorder-service

server.port=8080

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=15GB
spring.servlet.multipart.max-request-size=15GB
server.tomcat.max-http-post-size=15GB

spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

confidence-threshold=0.7

# for accident_database [own]
spring.datasource.url={SPRING_DATASOURCE_URL}
spring.datasource.username={SPRING_DATASOURCE_USERNAME}
spring.datasource.password={SPRING_DATASOURCE_PASSWORD}

# for accident-storage [own]
minio.endpoint={MINIO_ENDPOINT}
minio.access-key={MINIO_ACCESS_KEY}
minio.secret-key={MINIO_SECRET_KEY}

# for accident-broker [outer]
spring.kafka.bootstrap-servers=accident-broker:9092

spring.kafka.topic.accidents.name=accident-events

spring.kafka.consumer.accidents.group-id=accidents-consumer-group
spring.kafka.consumer.accidents.auto-offset-reset=latest
spring.kafka.consumer.accidents.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.accidents.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.accidents.properties.spring.json.trusted.packages=*
spring.kafka.consumer.accidents.properties.spring.json.use.type.headers=false

# for track-storage [outer]
spring.data.mongodb.host=track-storage
spring.data.mongodb.port=27017
spring.data.mongodb.database=track-storage
spring.data.mongodb.username=ivan-student
spring.data.mongodb.password=ivan-student
spring.data.mongodb.authentication-database=admin

spring.data.mongodb.connection-pool.max-size=10
spring.data.mongodb.connection-pool.min-size=2
spring.data.mongodb.connection-pool.max-wait-time=120000
spring.data.mongodb.connection-pool.max-connection-life-time=0
spring.data.mongodb.connection-pool.max-connection-idle-time=0